# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200521_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(default='alexford', max_length=150),
            preserve_default=False,
        ),
    ]
