# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20200521_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='author',
        ),
    ]
